#Tracker
language: cpp
os: linux

git:
  depth: 3
  quiet: true

branches:
    only:
        - master

env:
    global:
        APT_INSTALL="sudo apt-get install -y"

matrix:
  include:
      #- env:
          #- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
          #- OPT_BLAS_INT64=On
      #- env:
          #- BLAS_INT64=On OPT_PYTHON=On OPT_MATLAB=Off
          #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=/usr/bin/gfortran-7"
      #- env:
          #- BLAS_INT64=Off OPT_PYTHON=On OPT_MATLAB=Off
          #- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && FC=/usr/bin/gfortran-7"
      - env:
          - BLAS_INT64=On OPT_PYTHON=Off OPT_MATLAB=Off
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - env:
          - BLAS_INT64=Off OPT_PYTHON=Off OPT_MATLAB=Off
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

      ##Documentation build
      - env: DOC=On PDFDOC=On DOPT_BLAS_INT64=Off
        script: ./scripts/pdf-doc-build.sh
        dist: xenial #supports newer doxygen

#MATRIX_EVAL allows CC and CXX to be set before dependencies are installed
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - eval "${MATRIX_EVAL}"

install:
    - if [ "${DOC}" == "On" ]; then $APT_INSTALL doxygen graphviz; fi
    - if [ "${PDFDOC}" == "On" ]; then $APT_INSTALL doxygen-latex; fi
    - if [ "${CXX}" == "g++-4.9" ]; then $APT_INSTALL g++-4.9; fi
    - if [ "${CXX}" == "g++-5" ];   then $APT_INSTALL g++-5; fi
    - if [ "${CXX}" == "g++-6" ];   then $APT_INSTALL g++-6; fi
    - if [ "${CXX}" == "g++-7" ];   then $APT_INSTALL g++-7; fi
    - $APT_INSTALL libarmadillo-dev

script:
    - ./scripts/travis-build-test.sh

deploy:
    name: Docu-Bot
    provider: pages
    skip-cleanup: true
    github-token: $GH_TRAVISCI_DOCUMENTATION_TOKEN
    keep-history: true
    verbosed: true
    local_dir: _build/documentation/doc/html
    on:
        branch: master
        condition: $DOC = On
